---
title: 'RMarkdown:  In Class Assignment'
author: "Daniel Gil-Cardenas"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

### Wise Words

>["Pay no mind to those who talk behind your back, it simply means that you are two steps ahead."](https://minimalistquotes.com/tupac-shakur-quote-23822/)

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

### My Semester

|**Class**|**Course Number**|**Professor**|
|:--------|:-----------|:------------|
|Data Science|21352|Professor Shoemaker
|The Meaning of Life|23130/23200|Professor Bohorquez
|Intro to Proofs|21750|Professor Douglas
|Probability and Statistics|21755|Professor King


3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

### I Recommend

+ A _subsubheading_ with the name of the artist or author;   

+ An example of their writing or lyrics (formatted in a *plain code block*);

+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).  

_Cage the Elephant_

```
Afraid of what the truth might bring
He locks his doors and never leaves 
Desperately searching for signs
```

* Telescope
* Ready To Let Go
* Black Madonna
* Aint No Rest For The Wicked



Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
